### ISSUE TITLE
Move Config-Gets From Execute to Init@BangbangTransport,BangbangFlywheel,TurretBangbang

### ISSUE THREAD

**Issue by karkason** [frc3316/Stronghold2016#14]
Move all `onVoltage = (double) config.get("turret_Bangbang_OnVoltage");` statements from the exectue method to the init method.

The value can't change during the runtime of the command, and the config.get method's worst case time complexity is O(log n).

**Comment by frc3316** [comment]
This was purposely dont in order to allow the value to change during runtime, for testing purposes. If it really matters I'll change it.

**Comment by ThinkRedstone** [comment]
You should leave it as is. O(log n) on such a small n doesn't really matter, and the ability to debug (D-bug?) in runtime for default commands and other non-finishing commands is nice.

**Comment by karkason** [comment]
Re-running gets where it won't be needed (a command that finishes before you can grab your mouse to update the values) makes no sense.
If you'll take a look at the PR we're leaving them only on commands where it would make sense to change values during runtime(e.g. TankDrive).
